### ISSUE TITLE
headers.canonical_string always includes http_method

### ISSUE THREAD

**Issue by DiegoSalazar** [mgomes/api_auth#129]
The `with_http_method` option is ignored by `ApiAuth::Headers#canonical_string` which breaks older clients that are not yet including the http_method in their canonical_string.

https://github.com/mgomes/api_auth/blob/master/lib/api_auth/headers.rb#L57

**Comment by kjg** [comment]
This is the expected behavior of v2.x which is backward incompatible with clients that don't include the http_method. The server side code needs to be using 1.4.x or 1.5.x in order to handle both versions of canonical_string.

Checkout our upgrade strategy for more info https://github.com/mgomes/api_auth/blob/master/CHANGELOG.md#140-2015-12-16

**Comment by DiegoSalazar** [comment]
Is v1.5 compatible with Rails 5?

**Comment by kjg** [comment]
I have not tested v1.5 against rails 5, but I don't think there have been any rails specific changes made to ApiAuth since v1.5 other than accounting for [this deprecation ](https://github.com/mgomes/api_auth/commit/3a51d474a934a5f66d3bf7502202e8db8d33e9d5).

Therefore I believe v1.5 should work with rails 5, but if not, I'd be happy to release a new 1.x with any fixes needed. Just let me know. Thanks!
