### ISSUE TITLE
Allow configuration of requests signature timeout

### ISSUE THREAD

**Issue by ksol** [mgomes/api_auth#80]
Hello,

I was wondering if you would be willing to accept a PR adding support for configuring the timeout delay for signed requests.

15mn is very fine for production environments, but I'd like to allow a greater delay in staging environments, so that developers implementing the authentication scheme don't have to change the header `Date` and their signature every 15mn.

I'm more than willing to open a PR with code + tests for this feature, but I'd like to know if this is something you'd accept first.

In any case, thanks for your work on this gem, and have a nice day !

**Comment by awendt** [comment]
Not sure I understand you correctly. Your comment "so that developers […] don't have to change […] their signature every 15mn" reads like they are manually signing requests.

You'd usually want to sign requests not by hand but using an SDK (like this gem provides with [`ApiAuth.sign!`](https://github.com/mgomes/api_auth#http-client-objects)).

Signing in this way happens instantly and the required `Date` can be dynamic. If you do that, do you really need a longer timeout? (Maybe I misread you, if so, can you elaborate on your use case?)

**Comment by ksol** [comment]
> You'd usually want to sign requests not by hand but using an SDK (like this gem provides with ApiAuth.sign!)

Yeah, but someone has to develop those when one is not already available :)

**Comment by awendt** [comment]
@ksol Sorry for not getting back sooner. You're welcome to make this configurable, the use case definitely makes sense and you're obviously not the only one – see referenced issue :)

**Comment by kjg** [comment]
Completed in #136
