### ISSUE TITLE
Is api-auth version 1.0.3 compatible with rails 3.0.0?

### ISSUE THREAD

**Issue by anantasur** [mgomes/api_auth#85]

**Comment by awendt** [comment]
We auto-run test against Rails 3 since #40 and the initial implementation of those tests targeted 1.1.0 (the successor of 1.0.3).

Looking at the [commits](https://github.com/mgomes/api_auth/commits/ced290c92845ec192372024d4bcdc03b348ca8d0) I guess it's safe to say 1.0.3 is compatible even though I'd encourage you to upgrade to a recent version which is tested against Rails 3.0.20
